### ISSUE TITLE
Preview image for user-drawn character is oversize when first viewed in the project page

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchjr#98] opened 2016-05-20 14:10 UTC
When you first draw a character from scratch in the paint editor, and return to the project page, the preview image is too large (you can see in the screenshot that it extends out of the visible scripting area). When you navigate away from the project page and return to it, however, the preview image for that character is rendered correctly. It's only the initial render that seems to be buggy.

(This was in Scratch Jr downloaded from the Amazon Apps store on May 19, 2016; Amazon tablet Fruity Pebbles.)

![img_7116](https://cloud.githubusercontent.com/assets/1320456/15430316/cac86282-1e72-11e6-97c9-6fc48464b349.JPG)

**Comment by chrisgarrity** [comment] 2021-05-05 17:20
closing as duplicate of https://github.com/LLK/scratchjr/issues/63

**Closed by chrisgarrity** 2021-05-05 17:20 UTC
Labels: prio-low
