### ISSUE TITLE
Can't import .sjr file

### ISSUE THREAD

**Issue by anitawoodruff** [LLK/scratchjr#158] opened 2017-12-14 12:30 UTC
Nexus 10 on Android L (5.0.2)
ScratchJr version 1.2.5

I can export projects created on this tablet via email, and then import them back by opening the attachment from my sent mail, but I can't import a project that my niece sent me (I believe it was created with ScratchJr on an Android tablet also).

When I tap on the attachment in Gmail it just pops up saying "You don't have an app that can open this file (.sjr)".

**Comment by anitawoodruff** [comment] 2017-12-14 12:34
Attached here (had to manually add '.zip' to the filepath to upload it)
[let'scomeandplaysong.sjr.zip](https://github.com/LLK/scratchjr/files/1559156/let.scomeandplaysong.sjr.zip)

**Comment by thisandagain** [comment] 2017-12-18 20:43
@anitawoodruff Can you give us some details on the Android device and OS version that is being used to create and import the file? Thanks!

**Comment by chmelvv** [comment] 2018-01-04 15:39
Hi, thanks for your work!
I have the same problem. 
1) Project was created with Scratch Jr on Samsung Galaxy Tab 2 10,1, Android 4.4. 
2) Exported  via email.
3) I try to import it 
   a) on the same device after factory reset - it is failed.
   b) On the same device but with Android 5.5 - it is failed also.

Is any another way to import project inside installed ScratchJr (May be unzip, put to some folder, etc.)?

**Comment by beskrovnykh** [comment] 2018-09-28 10:49
I have the same problem experimenting with two tablets on Android 7.0

1. Create new project with Scratch Jr. 1.2.5 add some blocks and press share by email
2. Send email
3. Open email via gmail and click the link
Result: file was opened as zip
4. Open email via aquamail and click on the link
Result: Scratch Jr was opened, but I did not find any project there

After that I repeated these steps on Android 4.4.2 and still failed to import 

Expectations
3. I expected that OS will recognize sjr file and open the Scratch Jr app 
4. I expected to see new project with blue ribbon

@thisandagain can you please have a look on that. I can explain steps to reproduce the problem and assist to fix it. Thanks.

**Comment by charleshuangruo** [comment] 2019-06-23 09:13
The same problem. I cannot import the .sjr file with Scratchjr after I have shared for the Android 9.0 tablet. There will not be any new projects on the main page. The problem still exists in version 1.2.6.

**Comment by ricardobigote** [comment] 2019-07-03 00:34
Hi!
"Open sjr files with ScratchJr" worked as it should for a while, but for some reason this as turned to be as issue since over 10 months ago!

**Is there a work around for this?**

Steps I've tried:
1- Download sjr file to Downloads folder;
2- Access that folder with a File APP (used "E S File Explorer" since default files APP doesn't recognize sjr file);
3- Press on file and select open with ScratchJr;
4- ScratchJr opens on start image window, but project doesn't load!

Samsung Galaxy Tab 3 SM-T310
Android 4.4.2
(have several other Android tablets and it doesn't work there either)


Thank you very much!
Cheers,

Ricardo Pinto

**Comment by yueyuzhao** [comment] 2019-07-03 02:01
- If there is more than one dot in the file name like `let.scomeandplaysong.sjr`, ScratchJr won't pop up. This can be fixed if we rename the project file.
- ScratchJr can only open files with mime type `application/x-scratchjr-project`, but the mime type of some the attachments varies, mine is `application/mz-octet-stream`. Even if you force ScratchJr open the file like @ricardobigote did, the projects won't be imported because of `it != null && it.getType() != null && it.getType().equals(PROJECT_MIMETYPE)` in `ScratchJrActivity.java` on line 152.

@chrisgarrity Can we just validate the extension to allow users to open the projects?

**Comment by chrisgarrity** [comment] 2019-07-03 12:54
@yueyuzhao in an ideal world the mime-type wouldn't get changed from the type set when it's exported, but unfortunately that's not what happens. I've marked this as help-wanted. If someone wants to submit a PR that checks the extension if the mime-type doesn't match to allow `.sjr` we'd definitely consider accepting it. Please note that to support the PBS Kids version of ScratchJr, it should also check for `.psjr` as those projects have a different extension.

**Comment by charleshuangruo** [comment] 2019-07-03 15:43
@chrisgarrity So in Android system, why does the .sjr file cannot be opened and generate the project from file explorer apps (like ES File Explorer or built-in one) and the process can be done only by clicking the shared attachment inside Gmail and Aquamail app?

In terms of the iOS version of ScratchJr, the local .sjr file can be opened and generate the project by file explorer app, e.g., File Hub with ease. What is the difference between these two mechanisms? 

In addition, I think the email-sharing function is more or less weird. Therefore, I suggest adding a function to export (save) .sjr file to phone's flash drive. Thus users are able to open the .sjr file in file explorer app (after fixing the issue above) and share the file freely as they want.

**Comment by ricardobigote** [comment] 2019-07-07 11:17
> @yueyuzhao in an ideal world the mime-type wouldn't get changed from the type set when it's exported, but unfortunately that's not what happens. I've marked this as help-wanted. If someone wants to submit a PR that checks the extension if the mime-type doesn't match to allow `.sjr` we'd definitely consider accepting it. Please note that to support the PBS Kids version of ScratchJr, it should also check for `.psjr` as those projects have a different extension.

Hi @chrisgarrity!
Sorry for insisting... I understand that the mime-type is somehow android dependent.
But is there a way to manually edit/change the mime-type and force import projects to ScratchJr?

**Comment by ricardobigote** [comment] 2019-07-08 19:07
> @chrisgarrity So in Android system, why does the .sjr file cannot be opened and generate the project from file explorer apps (like ES File Explorer or built-in one) and the process can be done only by clicking the shared attachment inside Gmail and Aquamail app?
> 
> In terms of the iOS version of ScratchJr, the local .sjr file can be opened and generate the project by file explorer app, e.g., File Hub with ease. What is the difference between these two mechanisms?
> 
> In addition, I think the email-sharing function is more or less weird and out-dated. Take as an example the scenario that someone is still using email to store important files, while others have been using the cloud drive (e.g., iCloud and Amazon Drive) to do it for many years.
> 
> Therefore, I suggest adding a function to export (save) .sjr file to phone's/tablet's flash memory (internal storage). Thus users are able to open the .sjr file in file explorer app (after fixing the issue above) and share the file freely as they want.

**I can confirm that Aquamail client APP has temporarily solved my problem.**

So, as I understand it, MIME type should be a part of the file, identifying the content type of the file. But that is not true, since MIME Types are not solved the same way in all OS's! Windows uses the 3 letter suffixes and MacOS / UNIX uses type number codes close to the MIME model.

Somehow GMail APP is wrongly guessing the MIME type, right?

**Comment by calas** [comment] 2020-01-11 12:52
Still an issue. Can't we just have an "Open file" option in ScratchJr? My son's tablet is very resource limited and I can't install another app already.

**Closed** 2020-04-21 11:53 UTC
