### ISSUE TITLE
"Waiting" - race condition with auto-save and save triggered by returning to project list

### ISSUE THREAD

**Issue by jwzimmer** [LLK/scratchjr#93] opened 2016-05-19 19:02 UTC
Hard to reproduce! But @chrisgarrity and I both saw it on two devices, so there is a bug.

While editing a project, sometimes clicking on the home icon causes "Waiting" to appear in a speech bubble on the ScratchJr logo. @chrisgarrity said that probably what is happening is that there is a race condition between the auto-save and the save triggered by clicking on the home icon to return to the project list.

(This was in Scratch Jr downloaded from the Amazon Apps store on May 19, 2016; Amazon tablet Fruity Pebbles.)

**Comment by d97ulf** [comment] 2017-02-26 09:49
I'm experiencing the same issue on all 3 of my Android tabs. One Samsung SMT-365, and two Lenovo A7-10 (two different generations).

In one view it says "Saving" for a long time, when going back and then trying to hit the "Home" button the "Waiting" label is attached and I have to kill the application.

**Comment by chrisgarrity** [comment] 2017-02-27 14:06
@d97ulf Sorry to hear that you're getting this issue. Usually this happens when a save gets triggered while the project is autosaving, so nothing should get lost when you kill the application as it's already saved.

**Comment by cuistax** [comment] 2017-04-21 19:00
Hello! We installed the app this morning on my son's tablet, a Samsung Galaxy Tab E, and we've experienced the issue described here several times already (four times exactly today). So the issue may be more widespread/severe than you think. And in our case, unlike what was stated above, the projects did /not/ get saved so we had to redo our changes each time. Hope a fix will be found soon ;)

**Comment by gandolfi974** [comment] 2018-02-14 06:50
hi, i have the same problem with my student. the project is not save and they lost all the work.

i hope a fix can be found.

**Comment by botchniaque** [comment] 2018-02-17 11:53
We're seeing that problem on any Android tablet we use. It's super frustrating because all the work is lost as soon as this problem kicks in. It really spoils all the fun.

**Comment by klausw** [comment] 2018-06-04 23:52
So far, my daughters lost work both times they used the app :-/

I was poking around in the source a bit, and I'm confused about how it works. For example, Runtime.beginTimer sets `Project.saving = false`, and ScratchJr's autosave checks `!Project.saving`.

However, as far as I can tell Project.js doesn't actually export the 'saving' attribute? There's a file-level variable `let saving = false`, but that's outside the class definition, and there's no accessor for it defined in the Project class. My knowledge about JS modules is rusty - is this supposed to be auto-exported at the module level?

My suspicion is that `Project.saving` and Project.js's `saving` are two completely independent variables, and autosaving would be unaware of a project-level save being in progress. Does that seem plausible?

Just to confuse matters further, there's also a `let saving = false` in Paint.js, and that has a `static get saving ()` accessor, but this seems independent from the project-level one.

**Comment by chrisgarrity** [comment] 2018-06-05 21:38
@klausw sorry to hear your daughters lost work. Thanks for the investigation, it sounds like a plausible root cause.

**Comment by chrisgarrity** [comment] 2018-10-22 18:19
Some further notes:
It's consistently reproducible on Android with the following steps:
1. Open a project and make some changes
2. Click the Android home button.
3. Wait some amount of time, maybe around 20-30 seconds (sorry I can't be more specific)
4. Reopen ScratchJr - you'll see 'Saving' followed by 'waiting',
There's an error in the console (unfortunately the line numbers are useless):
```
VM1265:1 Uncaught SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at app.bundle.js:1
    at Function.value (app.bundle.js:1)
    at Function.value (app.bundle.js:1)
    at Function.value (app.bundle.js:1)
    at Function.value (app.bundle.js:1)
    at Function.value (app.bundle.js:1)
    at Function.value (app.bundle.js:1)
    at app.bundle.js:1
(anonymous) @ app.bundle.js:1
value @ app.bundle.js:1
value @ app.bundle.js:1
value @ app.bundle.js:1
value @ app.bundle.js:1
value @ app.bundle.js:1
value @ app.bundle.js:1
(anonymous) @ app.bundle.js:1
setInterval (async)
value @ app.bundle.js:1
(anonymous) @ app.bundle.js:8
value @ app.bundle.js:1
t.editorMain @ app.bundle.js:8
value @ app.bundle.js:1
e @ app.bundle.js:8
(anonymous) @ app.bundle.js:8
(anonymous) @ app.bundle.js:1
a.onreadystatechange @ app.bundle.js:1
XMLHttpRequest.send (async)
value @ app.bundle.js:1
value @ app.bundle.js:1
(anonymous) @ app.bundle.js:8
(anonymous) @ app.bundle.js:1
a.onreadystatechange @ app.bundle.js:1
XMLHttpRequest.send (async)
value @ app.bundle.js:1
value @ app.bundle.js:1
(anonymous) @ app.bundle.js:8
(anonymous) @ app.bundle.js:8
a.onreadystatechange @ app.bundle.js:1
XMLHttpRequest.send (async)
value @ app.bundle.js:1
(anonymous) @ app.bundle.js:8
window.onload @ app.bundle.js:8
load (async)
(anonymous) @ app.bundle.js:8
a @ app.bundle.js:1
(anonymous) @ app.bundle.js:1
(anonymous) @ app.bundle.js:1
```

This probably isn't quite the same as clicking the home button, but related. ScratchJr probably isn't handling the lifecycle events related to low memory, or otherwise getting swapped out.

**Comment by yueyuzhao** [comment] 2018-11-02 12:07
A quick way to reproduce this issue:

1. Change `autoSaveInterval` in `settings.json` to 3000 and build it
2. Enter to editor page and do some change quick change before ScratchJr auto saving
3. Press home button

You will receive `Uncaught SyntaxError: Unexpected token S in JSON at position 0` in the Log of Android Studio, and reopen ScratchJr, you will see the waiting message.

**Comment by yueyuzhao** [comment] 2018-11-02 12:13
When ScratchJr entering to background, `ScratchJrActivity@onPause` method will be called, and the database will be closed, but the auto saving function is still working, and `DatabaseException` will be throwed up and a `SQL error: ` string is returned back to the project. That's why `Uncaught SyntaxError: Unexpected token S in JSON at position 0`

**Comment by yueyuzhao** [comment] 2018-11-02 12:17
Before closing the database, in `ScratchJrActivity@onPause` will run `if (typeof(ScratchJr) !== 'undefined') ScratchJr.onPause();`, but ScratchJr is not exposed to global, so ScratchJr is not paused correctly. I'll open a pull request for a quick fix.

**Closed** 2019-04-15 16:42 UTC
Labels: help wanted, prio-medium
