### ISSUE TITLE
Don't allow resize of the window on chromebooks

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#409] opened 2021-04-26 20:42 UTC
### Expected Behavior
The best experience for ScratchJr is at fullscreen, especially for young children. Even on chromebooks ScratchJr should enforce that it runs in full screen mode.

### Actual Behavior
Chromebooks run Android apps in a window and allow the user to resize the window. It's possible for users to make the window much too small to be usable.

**Comment by BryceLTaylor** [comment] 2021-05-04 14:00
Closing as duplicate of https://github.com/LLK/scratchjr/issues/403

**Closed by BryceLTaylor** 2021-05-04 14:00 UTC
Labels: android
