### ISSUE TITLE
Old Chrome version doesn't work on newer ChromeOS

### ISSUE THREAD

**Issue by chrisgarrity** [LLK/scratchjr#161] opened 2018-03-08 16:55 UTC
We haven't updated the Chrome Web Store version of ScratchJr as ARC Welder is no longer supported by Google and the recommended process is to install from Google Play. It appears that the old version flickers on the launch screen (or goes black) with newer versions of Chrome OS. Here's a report from a user (with video):

Good afternoon,

I have attached a video to demonstrate how the Scratch Jr. program is glitching seemingly on certain Chrome OS versions.

 As you can see, the version 63 on the left works fine, however, the updated version 65 on the right does not work with the program. We are using Acer C740 model Chromebooks.

 
![chromeos-flicker](https://user-images.githubusercontent.com/399209/37164160-8c351bfe-22c7-11e8-9873-b3aaf21a4798.gif)

**Comment by mrscanning** [comment] 2020-04-09 18:00
My school  district just put the scratchjr app on our student chrome books. It does not move past the school, home, other screen.  Is there anything IT can do differently on their end to get this working?  Does any one else have this problem?  This is the model we are using.  They are new this year.
HP Chromebook 11A G6 EE
Product ID# 6kj19UT#ABA (Not sure if anyone would need this!)

Someone please help!  We need to use scratch JR for a Project Lead the Way module that we are trying to start teaching district-wide!

canningj@casdschools.org

**Comment by ajanian** [comment] 2020-09-09 15:07
My guess is that @mrscanning issue is a duplicate of https://github.com/LLK/scratchjr/issues/160 which I also have.  My Chromebook does not have a touchscreen yet still suffers from the same issue as 160 (mouse clicks don't register).

**Closed** 2022-03-09 16:18 UTC
Labels: chrome os, needs repro
